# Tutorial 1, ES 413 Deep Learning 2022-23

Learning outcomes:
- Handling packages
- Introduction to NumPy and Pandas
- Playing with NumPy functionalities
- Acessing GPU


## Handling Packages

Use `!` before commands to run in colab

We will be mainly using pip to install packages.


By default many packages are installed when you open a colab instance. If you want to install new packages which is not already present in the colab you can use the below listed syntax.

Syntax:

Install the latest version of a package: `!pip install package_name` \\
Example: `!pip install numpy`

Install a particular version of a package: `!pip install package_name==version_number` \\
Example:`!pip install numpy==1.21.5`

In [ ]:
!pip list -v

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
print(np.version.version)

In [ ]:
!pip install numpy==1.21.5

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 15.7 MB 6.9 MB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6


In [ ]:
import numpy as np
print(np.version.version)


### <font color='red'> Try it</font> 

- Install the latest version of the package `transformers` 
- Install the `4.20.0` version of `transformers`

Question: How do I know what version I need and what all are the avialable versions?



In [ ]:
# Write your command here
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 6.1 MB/s 
     |████████████████████████████████| 182 kB 10.2 MB/s 
     |████████████████████████████████| 7.6 MB 37.0 MB/s 


In [ ]:
# Write your command here


In [ ]:
import transformers
print(transformers.__version__)

4.25.1


## Numpy

It is important to know how to find functionalities that you need without anyone explicitly instructing or debug an issue. Some of the common ways of doing is this are:

- Read the documentation of the package
- Simple Google search
- Stackoverflow answers

In [ ]:
!pip install numpy==1.21.6

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 15.7 MB 8.2 MB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5


In [ ]:
import numpy as np
print(np.version.version)

1.21.6


### Arrays

The holy chalice of numpy. `ndarray` is multidimensional table of elements of the same **type**. The dimensions of the array are called the axes.

#### Creating

In [ ]:
my_array = np.array([1,2,3,4,5])
# my_array = np.array([1.4,2.9,3.1,4.5,5.0])
# my_array = np.array(['Hello','There'])
# my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# my_array = np.arange(24)   

my_array = np.zeros((3, 4)) # Array of zeros of the desired shape
# my_array = np.ones((3,4)) # Array of ones of the desired shape

# Trivial examples
# my_array = np.array([[1,2,3,4,5],[6,7,8,9,10,11]])

print("Array: ",my_array)
print("Type: ",my_array.dtype)
print("Size: ",my_array.size)
print("Shape: ",my_array.shape)

Array:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Type:  float64
Size:  12
Shape:  (3, 4)


Note: (1,5) is a two dimensional array, whereas (5,) is a one dimensional array

##### <font color='red'> Try it</font> 
- Create a `ndarray` of shape (54,2,1) filled with zeros.
- Create an one dimensional array consisting of the first 50 natural numbers


In [ ]:
# Write your code here


In [ ]:
# Write your code here

#### Reshaping arrays

In [ ]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array: \n",my_array)
print("Original array shape: ",my_array.shape)

print()

flat_array = my_array.ravel()
print("Flattened array: \n",flat_array)
print("Flattened array shape: ",flat_array.shape)

print()

reshaped_array = my_array.reshape((5,2))
print("Flattened array: \n",reshaped_array)
print("Flattened array shape: ",reshaped_array.shape)

Original array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Original array shape:  (2, 5)

Flattened array: 
 [ 1  2  3  4  5  6  7  8  9 10]
Flattened array shape:  (10,)

Flattened array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Flattened array shape:  (5, 2)


##### <font color='red'> Try it</font> 

- Create an array of first 12 natural numbers, and reshape it into of shapes (4,3) and (3,4).

#### Indexing and Slicing
For one dimensional arrays(N,) single index is valid. \\

For multi-dimensional array index each axis seperately.

In [ ]:
# my_array = np.array([1,2,3,4,5])
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print("Array: \n",my_array)
print("Type: ",my_array.dtype)
print("Size: ",my_array.size)
print("Shape: ",my_array.shape)

# print("Indexed element/s:",my_array[1])
print("Indexed element/s:",my_array[1,2]) # access the element present [1,2] in the array
# print("Indexed element/s:",my_array[1]) # access all the elements in first row or my_array[1,:]

# print("Slice: ", my_array[1:3])
# print("Slice: ", my_array[1:3,3:5])



Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Type:  int64
Size:  15
Shape:  (3, 5)
Indexed element/s: 8


##### <font color='red'> Try it</font> 
Create an one dimensional array of the first 20 natural numbers. Reshape the array into of size (5,4)

- Find all elements in the 2nd row
- Find all elements in the 3rd column
- Find the element present in the 1st rows and 2nd column
- Find all the elements in the last two rows and first two columns



In [ ]:
# Write your code here

In [ ]:
# Write your code here

In [ ]:
# Write your code here

In [ ]:
# Write your code here

#### Vectorization

In [ ]:
list_a = list(range(0, 10000))
list_b = list(range(0, 10000))

arr_a = np.array(list_a)
arr_b = np.array(list_b)

In [ ]:
def multiply_lists(la, lb):
    for i in range(len(la)):
        la[i] * lb[i]

def multiply_np_arrays(arr_a, arr_b):
    arr_a * arr_b

In [ ]:
%timeit -n 100 -r 5 multiply_lists(list_a, list_b)

%timeit -n 100 -r 5 multiply_np_arrays(arr_a, arr_b)

1.11 ms ± 63.2 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)
8.66 µs ± 3.28 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)


NumPy delegates the loop to pre-compiled, optimized C code under the hood. This process is called vectorization of the multiplication operator. Vectorization of a function means that the function is now applied simultaneously over many values instead of a single value.

**Vectorized functions**

Can we also vectorize functions?

In [ ]:
l = np.random.rand(100000)
s = 94

In [ ]:
def foobar(i, s):
    if i < s:
        return s-i
    else:
        return i+s

In [ ]:
%timeit -n 100 -r 3 [foobar(x, s) for x in l]

68.9 ms ± 11.8 ms per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [ ]:
vectorized_foobar = np.vectorize(foobar)

In [ ]:
%timeit -n 100 -r 3 vectorized_foobar(l, s)

26 ms ± 840 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


#### Operations

In [ ]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original array: \n",my_array)
print()

# Assignment
my_array[1,3] = 11
print("Array after assignment : \n",my_array)
print()

my_array2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
# Element wise Addition/Subtraction/multiplication/division
opp_array = my_array + my_array2
print("Element wise operated array : \n",opp_array)
print()

#Single number Addition/Subtraction/multiplication/division
single_opp_array = my_array / 2
print("Single element operated array : \n",single_opp_array)



Original array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Array after assignment : 
 [[ 1  2  3  4  5]
 [ 6  7  8 11 10]]

Element wise operated array : 
 [[12 14 16 18 20]
 [22 24 26 30 30]]

Single element operated array : 
 [[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  5.5 5. ]]


##### <font color='red'> Try it</font> 

`array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])` \\
`array_2 = np.array([11,12,13,14,15],[16,17,18,19,20])` \\
`x = 3` \\
`y = 2` \\

- Find an array where each element of `array_1` is multiplied by `x` and the resulting element is incremented by `y`
- Subtract the corresponding elements of `array_1` from `array_2`, and increment each element of the resulting array by `x*y`


In [ ]:
# Write your code here

In [ ]:
# Write your code here

## Pandas

- Download the dataset from [here](https://datahub.io/machine-learning/iris/r/iris.csv) \\
- Upload the dataset to this colab notebook

CSV(Comma Separated Values) files are the most common of way of storing tabled data 

In [ ]:
import pandas as pd

In [ ]:
# reading a file
PATH_TO_THE_FILE = '/content/iris_csv.csv'
df = pd.read_csv(PATH_TO_THE_FILE)

In [ ]:
df

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'class'], dtype='object')

In [ ]:
df.shape

(150, 5)

### Slicing

- Column-wise slicing 
- Row-wise slicing : Similar to slicing a list

In [ ]:
# Row slicing
row_sliced_df = df[4:145]
row_sliced_df

sepallength  sepalwidth  petallength  petalwidth           class
4            5.0         3.6          1.4         0.2     Iris-setosa
5            5.4         3.9          1.7         0.4     Iris-setosa
6            4.6         3.4          1.4         0.3     Iris-setosa
7            5.0         3.4          1.5         0.2     Iris-setosa
8            4.4         2.9          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
140          6.7         3.1          5.6         2.4  Iris-virginica
141          6.9         3.1          5.1         2.3  Iris-virginica
142          5.8         2.7          5.1         1.9  Iris-virginica
143          6.8         3.2          5.9         2.3  Iris-virginica
144          6.7         3.3          5.7         2.5  Iris-virginica

[141 rows x 5 columns]

In [ ]:
# coloumn slicing
col_sliced_df = df[['sepallength','class']]
col_sliced_df

sepallength           class
0            5.1     Iris-setosa
1            4.9     Iris-setosa
2            4.7     Iris-setosa
3            4.6     Iris-setosa
4            5.0     Iris-setosa
..           ...             ...
145          6.7  Iris-virginica
146          6.3  Iris-virginica
147          6.5  Iris-virginica
148          6.2  Iris-virginica
149          5.9  Iris-virginica

[150 rows x 2 columns]

More sophasticated way of slicing

- iloc: Uses integer index of column/row
- loc: Uses name of column/row

In [ ]:
#Choosing the 5th,9th,89th row
# choosed_df = df[[5,9,89]]  # Wrong, will give you an error
choosed_df = df.iloc[[5,9,89]]
# choosed_df = df.iloc[5:89]
choosed_df


sepallength  sepalwidth  petallength  petalwidth            class
5           5.4         3.9          1.7         0.4      Iris-setosa
9           4.9         3.1          1.5         0.1      Iris-setosa
89          5.5         2.5          4.0         1.3  Iris-versicolor

In [ ]:
# Choosing rows and columns through iloc

choosed_df = df.iloc[4:100,2:4] # similar to 2d ndarray slicing
choosed_df

petallength  petalwidth
4           1.4         0.2
5           1.7         0.4
6           1.4         0.3
7           1.5         0.2
8           1.4         0.2
..          ...         ...
95          4.2         1.2
96          4.2         1.3
97          4.3         1.3
98          3.0         1.1
99          4.1         1.3

[96 rows x 2 columns]

In [ ]:
virginica_df = df.loc[df["class"] == "Iris-virginica"] # Conditioned slicing
virginica_df

sepallength  sepalwidth  petallength  petalwidth           class
100          6.3         3.3          6.0         2.5  Iris-virginica
101          5.8         2.7          5.1         1.9  Iris-virginica
102          7.1         3.0          5.9         2.1  Iris-virginica
103          6.3         2.9          5.6         1.8  Iris-virginica
104          6.5         3.0          5.8         2.2  Iris-virginica
105          7.6         3.0          6.6         2.1  Iris-virginica
106          4.9         2.5          4.5         1.7  Iris-virginica
107          7.3         2.9          6.3         1.8  Iris-virginica
108          6.7         2.5          5.8         1.8  Iris-virginica
109          7.2         3.6          6.1         2.5  Iris-virginica
110          6.5         3.2          5.1         2.0  Iris-virginica
111          6.4         2.7          5.3         1.9  Iris-virginica
112          6.8         3.0          5.5         2.1  Iris-virginica
113          5.7         2.5          5.0         2.0  Iris-virginica
114          5.8         2.8          5.1         2.4  Iris-virginica
115          6.4         3.2          5.3         2.3  Iris-virginica
116          6.5         3.0          5.5         1.8  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
119          6.0         2.2          5.0         1.5  Iris-virginica
120          6.9         3.2          5.7         2.3  Iris-virginica
121          5.6         2.8          4.9         2.0  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica
123          6.3         2.7          4.9         1.8  Iris-virginica
124          6.7         3.3          5.7         2.1  Iris-virginica
125          7.2         3.2          6.0         1.8  Iris-virginica
126          6.2         2.8          4.8         1.8  Iris-virginica
127          6.1         3.0          4.9         1.8  Iris-virginica
128          6.4         2.8          5.6         2.1  Iris-virginica
129          7.2         3.0          5.8         1.6  Iris-virginica
130          7.4         2.8          6.1         1.9  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica
132          6.4         2.8          5.6         2.2  Iris-virginica
133          6.3         2.8          5.1         1.5  Iris-virginica
134          6.1         2.6          5.6         1.4  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica
136          6.3         3.4          5.6         2.4  Iris-virginica
137          6.4         3.1          5.5         1.8  Iris-virginica
138          6.0         3.0          4.8         1.8  Iris-virginica
139          6.9         3.1          5.4         2.1  Iris-virginica
140          6.7         3.1          5.6         2.4  Iris-virginica
141          6.9         3.1          5.1         2.3  Iris-virginica
142          5.8         2.7          5.1         1.9  Iris-virginica
143          6.8         3.2          5.9         2.3  Iris-virginica
144          6.7         3.3          5.7         2.5  Iris-virginica
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [ ]:
# Multiple conditioned slicing
long_virginica_df = df.loc[(df["class"] == "Iris-virginica") & (df['sepallength']>7)]
long_virginica_df

sepallength  sepalwidth  petallength  petalwidth           class
102          7.1         3.0          5.9         2.1  Iris-virginica
105          7.6         3.0          6.6         2.1  Iris-virginica
107          7.3         2.9          6.3         1.8  Iris-virginica
109          7.2         3.6          6.1         2.5  Iris-virginica
117          7.7         3.8          6.7         2.2  Iris-virginica
118          7.7         2.6          6.9         2.3  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica
125          7.2         3.2          6.0         1.8  Iris-virginica
129          7.2         3.0          5.8         1.6  Iris-virginica
130          7.4         2.8          6.1         1.9  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica

In [ ]:
mean_sepallength = df['sepallength'].mean()
sum_sepalwidth = df['sepalwidth'].sum()
median_petallength = df['petallength'].median()
min_petalwidth = df['petalwidth'].min()
max_petalwidth = df['petalwidth'].max()

print("Mean sepal length: ",mean_sepallength)
print("Sum of all sepal width: ",sum_sepalwidth)
print("Median petal length: ",median_petallength)
print("Minimum petal width: ",min_petalwidth)
print("Maximum petal width: ",max_petalwidth)

Mean sepal length:  5.843333333333334
Sum of all sepal width:  458.1
Median petal length:  4.35
Minimum petal width:  0.1
Maximum petal width:  2.5


### <font color='red'> Try it</font> 

- Find the petal width and petal class of the flower with minimum petal length
- Find the min and max sepal length of petals belonging to "Iris-setosa" class
- Check if the 90th row's sepal length is lesser than the 9th row's sepal length
- What is the most commonly occuring class in the dataset?

In [ ]:
# Write your code here


In [ ]:
# Write your code here


In [ ]:
# Write your code here


In [ ]:
# Write your code here


#### Basic operations

In [ ]:
res = df['sepalwidth'] + df['petallength']
res.values

array([ 4.9,  4.4,  4.5,  4.6,  5. ,  5.6,  4.8,  4.9,  4.3,  4.6,  5.2,
        5. ,  4.4,  4.1,  5.2,  5.9,  5.2,  4.9,  5.5,  5.3,  5.1,  5.2,
        4.6,  5. ,  5.3,  4.6,  5. ,  5. ,  4.8,  4.8,  4.7,  4.9,  5.6,
        5.6,  4.6,  4.4,  4.8,  4.6,  4.3,  4.9,  4.8,  3.6,  4.5,  5.1,
        5.7,  4.4,  5.4,  4.6,  5.2,  4.7,  7.9,  7.7,  8. ,  6.3,  7.4,
        7.3,  8. ,  5.7,  7.5,  6.6,  5.5,  7.2,  6.2,  7.6,  6.5,  7.5,
        7.5,  6.8,  6.7,  6.4,  8. ,  6.8,  7.4,  7.5,  7.2,  7.4,  7.6,
        8. ,  7.4,  6.1,  6.2,  6.1,  6.6,  7.8,  7.5,  7.9,  7.8,  6.7,
        7.1,  6.5,  7. ,  7.6,  6.6,  5.6,  6.9,  7.2,  7.1,  7.2,  5.5,
        6.9,  9.3,  7.8,  8.9,  8.5,  8.8,  9.6,  7. ,  9.2,  8.3,  9.7,
        8.3,  8. ,  8.5,  7.5,  7.9,  8.5,  8.5, 10.5,  9.5,  7.2,  8.9,
        7.7,  9.5,  7.6,  9. ,  9.2,  7.6,  7.9,  8.4,  8.8,  8.9, 10.2,
        8.4,  7.9,  8.2,  9.1,  9. ,  8.6,  7.8,  8.5,  8.7,  8.2,  7.8,
        9.1,  9. ,  8.2,  7.5,  8.2,  8.8,  8.1])

In [ ]:
df2 = df.copy()
df2

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df2['sepallength'] = df['sepallength']*-1
df2

sepallength  sepalwidth  petallength  petalwidth           class
0           -5.1         3.5          1.4         0.2     Iris-setosa
1           -4.9         3.0          1.4         0.2     Iris-setosa
2           -4.7         3.2          1.3         0.2     Iris-setosa
3           -4.6         3.1          1.5         0.2     Iris-setosa
4           -5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145         -6.7         3.0          5.2         2.3  Iris-virginica
146         -6.3         2.5          5.0         1.9  Iris-virginica
147         -6.5         3.0          5.2         2.0  Iris-virginica
148         -6.2         3.4          5.4         2.3  Iris-virginica
149         -5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df3 = df.copy()
df3['sepallength'] = df['sepalwidth'] + df['petallength']
df3

sepallength  sepalwidth  petallength  petalwidth           class
0            4.9         3.5          1.4         0.2     Iris-setosa
1            4.4         3.0          1.4         0.2     Iris-setosa
2            4.5         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          8.2         3.0          5.2         2.3  Iris-virginica
146          7.5         2.5          5.0         1.9  Iris-virginica
147          8.2         3.0          5.2         2.0  Iris-virginica
148          8.8         3.4          5.4         2.3  Iris-virginica
149          8.1         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df4 = df.copy()
df4['sum of sizes'] = df['sepallength'] + df['sepalwidth'] +  df['petallength'] +  df['petalwidth']
df4

sepallength  sepalwidth  petallength  petalwidth           class  \
0            5.1         3.5          1.4         0.2     Iris-setosa   
1            4.9         3.0          1.4         0.2     Iris-setosa   
2            4.7         3.2          1.3         0.2     Iris-setosa   
3            4.6         3.1          1.5         0.2     Iris-setosa   
4            5.0         3.6          1.4         0.2     Iris-setosa   
..           ...         ...          ...         ...             ...   
145          6.7         3.0          5.2         2.3  Iris-virginica   
146          6.3         2.5          5.0         1.9  Iris-virginica   
147          6.5         3.0          5.2         2.0  Iris-virginica   
148          6.2         3.4          5.4         2.3  Iris-virginica   
149          5.9         3.0          5.1         1.8  Iris-virginica   

     sum of sizes  
0            10.2  
1             9.5  
2             9.4  
3             9.4  
4            10.2  
..            ...  
145          17.2  
146          15.7  
147          16.7  
148          17.3  
149          15.8  

[150 rows x 6 columns]

In [ ]:
df.isnull()

sepallength  sepalwidth  petallength  petalwidth  class
0          False       False        False       False  False
1          False       False        False       False  False
2          False       False        False       False  False
3          False       False        False       False  False
4          False       False        False       False  False
..           ...         ...          ...         ...    ...
145        False       False        False       False  False
146        False       False        False       False  False
147        False       False        False       False  False
148        False       False        False       False  False
149        False       False        False       False  False

[150 rows x 5 columns]

In [ ]:
import numpy as np
# Create a dataframe with the 4th row filled with null/Nan
df_nulls = df.copy()
df_nulls.iloc[[4]] = np.nan
df_nulls

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            NaN         NaN          NaN         NaN             NaN
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df_nulls.isnull()

sepallength  sepalwidth  petallength  petalwidth  class
0          False       False        False       False  False
1          False       False        False       False  False
2          False       False        False       False  False
3          False       False        False       False  False
4           True        True         True        True   True
..           ...         ...          ...         ...    ...
145        False       False        False       False  False
146        False       False        False       False  False
147        False       False        False       False  False
148        False       False        False       False  False
149        False       False        False       False  False

[150 rows x 5 columns]

In [ ]:
df_nulls.fillna('0')

sepallength sepalwidth petallength petalwidth           class
0           5.1        3.5         1.4        0.2     Iris-setosa
1           4.9        3.0         1.4        0.2     Iris-setosa
2           4.7        3.2         1.3        0.2     Iris-setosa
3           4.6        3.1         1.5        0.2     Iris-setosa
4             0          0           0          0               0
..          ...        ...         ...        ...             ...
145         6.7        3.0         5.2        2.3  Iris-virginica
146         6.3        2.5         5.0        1.9  Iris-virginica
147         6.5        3.0         5.2        2.0  Iris-virginica
148         6.2        3.4         5.4        2.3  Iris-virginica
149         5.9        3.0         5.1        1.8  Iris-virginica

[150 rows x 5 columns]

### <font color='red'> Try it</font> 

Remember to copy the original dataframe or you might corrupt the data
- Add a new column "average_dimenion" that contains the average of sepal and petal lengths/widths

- During recording the data, all Iris-setosa petals where recorded 0.4 cm bigger that what they truly are and all Iris-virginica petals where recorded 0.1 cm smaller that what they truly are. Fix this.

- Reduce the petallength of all entries by 4 cm whose petallength is bigger than 4.5 cm

In [ ]:
# Write your code here


In [ ]:
# Write your code here


In [ ]:
# Write your code here


## Acessing GPU

Change your run time to allow Hardware accelerator via GPU.

Note: Free colab has limited GPU acess available, so do not try to run some huge models(it might not fit), and even if it does google might put you on timeout. Colab GPU is intended to some lightweight usage.

In the free version of Colab, notebooks can run for at most 12 hours, depending on availability and your usage patterns

In [ ]:
!nvidia-smi

Tue Jan  3 09:47:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    25W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Additional

Squeezing numpy array: `np.squeeze()` \\
Expanding the dimensions of an array: `np.expand_dims()`  \\
Common elements between two arrays: `np.intersect1d()` \\
Concatnating two arrays: `np.vstack()` and `np.hstack()`

Check out 100 Numpy excercises [here](https://github.com/rougier/numpy-100). 


In [ ]:
import numpy as np
arr1 = np.array([[[1,2,3,4,5]]])
print("Original shape: ",arr1.shape)
arr1_sqz = np.squeeze(arr1,axis=0)
print("Squeezed shape: ",arr1_sqz.shape)

Original shape:  (1, 1, 5)
Squeezed shape:  (1, 5)


In [ ]:
arr1 = np.array([1,2,3,4,5])
print("Original shape: ",arr1.shape)
arr1_sqz = np.expand_dims(arr1,axis=1)
print("Expanded array shape: ",arr1_sqz.shape)

Original shape:  (5,)
Expanded array shape:  (5, 1)


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,5,7,9])
print("Common elements: ",np.intersect1d(arr1,arr2))

Common elements:  [1 3 5]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,5,7,9])
vstack_arr = np.vstack((arr1,arr2))
hstack_arr = np.hstack((arr1,arr2))
print("Vertically stacked array: \n",vstack_arr)
print("Shape of vertically stacked array: ",vstack_arr.shape)

print("Horizontly stacked array: \n",hstack_arr)
print("Shape of horizontly stacked array: ",hstack_arr.shape)


Vertically stacked array: 
 [[1 2 3 4 5]
 [1 3 5 7 9]]
Shape of vertically stacked array:  (2, 5)
Horizontly stacked array: 
 [1 2 3 4 5 1 3 5 7 9]
Shape of horizontly stacked array:  (10,)
